# Generated by Django 4.2.16 on 2024-10-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sains', '0002_alter_tes_options_resultsains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultsains',
            options={'verbose_name_plural': 'Sains Result'},
        ),
    ]
