# Generated by Django 4.2.16 on 2024-10-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sains', '0003_alter_resultsains_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionSains',
        ),
    ]
