# Generated by Django 4.2.16 on 2024-10-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sains', '0004_rename_question_questionsains'),
    ]

    operations = [
        migrations.AddField(
            model_name='tes',
            name='command',
            field=models.CharField(default='isilah pertanyaan dibawah ini', max_length=255),
        ),
    ]
