# Generated by Django 4.2.16 on 2024-10-18 11:10

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_question', models.ImageField(blank=True, null=True, upload_to='pertanyaan/')),
                ('question', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('image_answer', models.ImageField(blank=True, null=True, upload_to='pertanyaan/')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
        ),
    ]
