# Generated by Django 4.2.16 on 2024-10-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pertanyaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaan',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
