# Generated by Django 4.2.16 on 2024-11-04 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=120)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='time in second')),
                ('command', models.CharField(default='isilah pertanyaan dibawah ini', max_length=255)),
                ('required_score_to_pass', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Tes',
            },
        ),
        migrations.CreateModel(
            name='ResultTes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesApp.tes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tes Result',
            },
        ),
        migrations.CreateModel(
            name='QuestionTes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('tes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesApp.tes')),
            ],
            options={
                'verbose_name_plural': 'Tes Questions',
            },
        ),
    ]
