# Generated by Django 4.2.16 on 2024-10-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='excerpt',
            field=models.CharField(help_text='untuk keterangan halaman', max_length=255),
        ),
    ]
